# Generated by Django 3.2.13 on 2022-04-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_note_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteimage',
            old_name='post',
            new_name='note',
        ),
    ]
