# Generated by Django 3.2.13 on 2022-04-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_rename_post_noteimage_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp_images/')),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='noteimage',
            name='image_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Full_stop.png/180px-Full_stop.png', max_length=500),
        ),
    ]
